package SysMod.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class GroupReference_Constraints extends BaseConstraintsDescriptor {
  /*package*/ GroupReference_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.GroupReference$oA, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.group$XaKq, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return ReferenceScopeProvider.fromHierarchy(CONCEPTS.Group$$t, new SNodePointer("r:1b15f564-ead2-4158-bee8-ce691366ba18(SysMod.constraints)", "2019826094428576445"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept GroupReference$oA = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca689dd2L, "SysMod.structure.GroupReference");
    /*package*/ static final SConcept Group$$t = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f0017L, "SysMod.structure.Group");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink group$XaKq = MetaAdapterFactory.getReferenceLink(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca689dd2L, 0x3f9799e4ca689dd4L, "group");
  }
}
