package SysMod.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class UserReference_Constraints extends BaseConstraintsDescriptor {
  /*package*/ UserReference_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.UserReference$mA, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.user$U$A4, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return ReferenceScopeProvider.fromHierarchy(CONCEPTS.User$vv, new SNodePointer("r:1b15f564-ead2-4158-bee8-ce691366ba18(SysMod.constraints)", "4893295416885818692"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept UserReference$mA = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L, "SysMod.structure.UserReference");
    /*package*/ static final SConcept User$vv = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03bcL, "SysMod.structure.User");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink user$U$A4 = MetaAdapterFactory.getReferenceLink(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L, 0x3f9799e4ca6051e1L, "user");
  }
}
