package SysMod.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Folder;
  private ConceptPresentation props_Group;
  private ConceptPresentation props_Permission;
  private ConceptPresentation props_System;
  private ConceptPresentation props_User;
  private ConceptPresentation props_UserList;
  private ConceptPresentation props_UserPermission;
  private ConceptPresentation props_UserReference;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Folder:
        if (props_Folder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Folder = cpb.create();
        }
        return props_Folder;
      case LanguageConceptSwitch.Group:
        if (props_Group == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Group = cpb.create();
        }
        return props_Group;
      case LanguageConceptSwitch.Permission:
        if (props_Permission == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Permission");
          props_Permission = cpb.create();
        }
        return props_Permission;
      case LanguageConceptSwitch.System:
        if (props_System == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_System = cpb.create();
        }
        return props_System;
      case LanguageConceptSwitch.User:
        if (props_User == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_User = cpb.create();
        }
        return props_User;
      case LanguageConceptSwitch.UserList:
        if (props_UserList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("UserList");
          props_UserList = cpb.create();
        }
        return props_UserList;
      case LanguageConceptSwitch.UserPermission:
        if (props_UserPermission == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("UserPermission");
          props_UserPermission = cpb.create();
        }
        return props_UserPermission;
      case LanguageConceptSwitch.UserReference:
        if (props_UserReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L, 0x3f9799e4ca6051e1L, "user", "", "");
          props_UserReference = cpb.create();
        }
        return props_UserReference;
    }
    return null;
  }
}
