package SysMod.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_DefGroup;
  private ConceptPresentation props_File;
  private ConceptPresentation props_Folder;
  private ConceptPresentation props_Group;
  private ConceptPresentation props_GroupReference;
  private ConceptPresentation props_ITarget;
  private ConceptPresentation props_Permission;
  private ConceptPresentation props_Root;
  private ConceptPresentation props_SetPermission;
  private ConceptPresentation props_SystemOp;
  private ConceptPresentation props_User;
  private ConceptPresentation props_UserLike;
  private ConceptPresentation props_UserList;
  private ConceptPresentation props_UserReference;
  private ConceptPresentation props_UserReferenceList;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.DefGroup:
        if (props_DefGroup == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Groups");
          props_DefGroup = cpb.create();
        }
        return props_DefGroup;
      case LanguageConceptSwitch.File:
        if (props_File == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_File = cpb.create();
        }
        return props_File;
      case LanguageConceptSwitch.Folder:
        if (props_Folder == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Folder = cpb.create();
        }
        return props_Folder;
      case LanguageConceptSwitch.Group:
        if (props_Group == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Group = cpb.create();
        }
        return props_Group;
      case LanguageConceptSwitch.GroupReference:
        if (props_GroupReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca689dd2L, 0x3f9799e4ca689dd4L, "group", "", "");
          props_GroupReference = cpb.create();
        }
        return props_GroupReference;
      case LanguageConceptSwitch.ITarget:
        if (props_ITarget == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ITarget = cpb.create();
        }
        return props_ITarget;
      case LanguageConceptSwitch.Permission:
        if (props_Permission == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Permission");
          props_Permission = cpb.create();
        }
        return props_Permission;
      case LanguageConceptSwitch.Root:
        if (props_Root == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Root");
          props_Root = cpb.create();
        }
        return props_Root;
      case LanguageConceptSwitch.SetPermission:
        if (props_SetPermission == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("SetPermission");
          props_SetPermission = cpb.create();
        }
        return props_SetPermission;
      case LanguageConceptSwitch.SystemOp:
        if (props_SystemOp == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SystemOp = cpb.create();
        }
        return props_SystemOp;
      case LanguageConceptSwitch.User:
        if (props_User == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_User = cpb.create();
        }
        return props_User;
      case LanguageConceptSwitch.UserLike:
        if (props_UserLike == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_UserLike = cpb.create();
        }
        return props_UserLike;
      case LanguageConceptSwitch.UserList:
        if (props_UserList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("UserList");
          props_UserList = cpb.create();
        }
        return props_UserList;
      case LanguageConceptSwitch.UserReference:
        if (props_UserReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L, 0x3f9799e4ca6051e1L, "user", "", "");
          props_UserReference = cpb.create();
        }
        return props_UserReference;
      case LanguageConceptSwitch.UserReferenceList:
        if (props_UserReferenceList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("UserReferenceList");
          props_UserReferenceList = cpb.create();
        }
        return props_UserReferenceList;
    }
    return null;
  }
}
