package SysMod.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_allowdeny extends EnumerationDescriptorBase {

  public EnumerationDescriptor_allowdeny() {
    super(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6c05a8L, "allowdeny", "r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353800439208");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_allow_0 = new EnumerationDescriptor.MemberDescriptor("allow", "allow", 0x3f9799e4ca6c05a9L, "r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353800439209");
  private final EnumerationDescriptor.MemberDescriptor myMember_deny_0 = new EnumerationDescriptor.MemberDescriptor("deny", "deny", 0x3f9799e4ca6c05aaL, "r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353800439210");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6c05a8L, 0x3f9799e4ca6c05a9L, 0x3f9799e4ca6c05aaL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_allow_0, myMember_deny_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "allow":
        return myMember_allow_0;
      case "deny":
        return myMember_deny_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
