package SysMod.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DefGroup = 0;
  public static final int File = 1;
  public static final int Folder = 2;
  public static final int Group = 3;
  public static final int GroupReference = 4;
  public static final int ITarget = 5;
  public static final int Permission = 6;
  public static final int SetPermission = 7;
  public static final int System = 8;
  public static final int User = 9;
  public static final int UserList = 10;
  public static final int UserReference = 11;
  public static final int UserReferenceList = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x248c097d53364d24L, 0x9241611e979642dbL);
    builder.put(0x1031032eecfe5cd0L, DefGroup);
    builder.put(0x3f9799e4ca6d5215L, File);
    builder.put(0x3f9799e4ca5f03a0L, Folder);
    builder.put(0x3f9799e4ca5f0017L, Group);
    builder.put(0x3f9799e4ca689dd2L, GroupReference);
    builder.put(0x3f9799e4ca69fd12L, ITarget);
    builder.put(0x3f9799e4ca5f40c8L, Permission);
    builder.put(0x3f9799e4ca6051dfL, SetPermission);
    builder.put(0x3f9799e4ca5efffbL, System);
    builder.put(0x3f9799e4ca5f03bcL, User);
    builder.put(0x3f9799e4ca5fa472L, UserList);
    builder.put(0x3f9799e4ca6051e0L, UserReference);
    builder.put(0x1031032eecfbf14bL, UserReferenceList);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
