package SysMod.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptFolder = createDescriptorForFolder();
  /*package*/ final ConceptDescriptor myConceptGroup = createDescriptorForGroup();
  /*package*/ final ConceptDescriptor myConceptPermission = createDescriptorForPermission();
  /*package*/ final ConceptDescriptor myConceptSystem = createDescriptorForSystem();
  /*package*/ final ConceptDescriptor myConceptUser = createDescriptorForUser();
  /*package*/ final ConceptDescriptor myConceptUserList = createDescriptorForUserList();
  /*package*/ final ConceptDescriptor myConceptUserPermission = createDescriptorForUserPermission();
  /*package*/ final ConceptDescriptor myConceptUserReference = createDescriptorForUserReference();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptFolder, myConceptGroup, myConceptPermission, myConceptSystem, myConceptUser, myConceptUserList, myConceptUserPermission, myConceptUserReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Folder:
        return myConceptFolder;
      case LanguageConceptSwitch.Group:
        return myConceptGroup;
      case LanguageConceptSwitch.Permission:
        return myConceptPermission;
      case LanguageConceptSwitch.System:
        return myConceptSystem;
      case LanguageConceptSwitch.User:
        return myConceptUser;
      case LanguageConceptSwitch.UserList:
        return myConceptUserList;
      case LanguageConceptSwitch.UserPermission:
        return myConceptUserPermission;
      case LanguageConceptSwitch.UserReference:
        return myConceptUserReference;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForFolder() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "Folder", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03a0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799586720");
    b.version(3);
    b.aggregate("userpermissions", 0x3f9799e4ca60cadeL).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051dfL).optional(true).ordered(true).multiple(true).origin("4582300353799703262").done();
    b.alias("Folder");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGroup() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "Group", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f0017L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799585815");
    b.version(3);
    b.aggregate("users", 0x3f9799e4ca5fa471L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5fa472L).optional(true).ordered(true).multiple(false).origin("4582300353799627889").done();
    b.alias("Group");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPermission() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "Permission", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L);
    b.class_(false, false, false);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799602376");
    b.version(3);
    b.property("read", 0x3f9799e4ca5f40e3L).type(PrimitiveTypeId.BOOLEAN).origin("4582300353799602403").done();
    b.property("write", 0x3f9799e4ca5f40e4L).type(PrimitiveTypeId.BOOLEAN).origin("4582300353799602404").done();
    b.property("execute", 0x3f9799e4ca5f40e5L).type(PrimitiveTypeId.BOOLEAN).origin("4582300353799602405").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSystem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "System", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5efffbL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799585787");
    b.version(3);
    b.aggregate("groups", 0x3f9799e4ca5f40e6L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f0017L).optional(true).ordered(true).multiple(true).origin("4582300353799602406").done();
    b.aggregate("folders", 0x3f9799e4ca5f40e7L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03a0L).optional(true).ordered(true).multiple(true).origin("4582300353799602407").done();
    b.alias("System");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUser() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "User", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03bcL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799586748");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUserList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "UserList", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5fa472L);
    b.class_(false, false, false);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799627890");
    b.version(3);
    b.aggregate("users", 0x3f9799e4ca5fa48dL).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03bcL).optional(true).ordered(true).multiple(true).origin("4582300353799627917").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUserPermission() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "UserPermission", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051dfL);
    b.class_(false, false, false);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799672287");
    b.version(3);
    b.aggregate("user", 0x3f9799e4ca60cab6L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L).optional(false).ordered(true).multiple(false).origin("4582300353799703222").done();
    b.aggregate("permission", 0x3f9799e4ca60cab7L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L).optional(false).ordered(true).multiple(false).origin("4582300353799703223").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUserReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SysMod", "UserReference", 0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca6051e0L);
    b.class_(false, false, false);
    b.origin("r:5562c3fd-8bed-4a60-8efa-3bbd60a507f0(SysMod.structure)/4582300353799672288");
    b.version(3);
    b.associate("user", 0x3f9799e4ca6051e1L).target(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f03bcL).optional(false).origin("4582300353799672289").done();
    return b.create();
  }
}
