package SysMod.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Permission__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L, "SysMod.structure.Permission");

  public static final SMethod<String> getVal_id7MUdLpgmQ_Y = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getVal").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8987556575348222334L).languageId(0x9241611e979642dbL, 0x248c097d53364d24L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getVal_id7MUdLpgmQ_Y);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getVal_id7MUdLpgmQ_Y(@NotNull SNode __thisNode__) {
    String conf = "";
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(__thisNode__, PROPS.read$Lqh8), 0x3f9799e4ca6c05a9L)) {
      conf += "r";
    } else {
      conf += "-";
    }
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(__thisNode__, PROPS.write$Lqw9), 0x3f9799e4ca6c05a9L)) {
      conf += "w";
    } else {
      conf += "-";
    }
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(__thisNode__, PROPS.execute$LqJa), 0x3f9799e4ca6c05a9L)) {
      conf += "x";
    } else {
      conf += "-";
    }
    return conf;
  }

  /*package*/ Permission__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getVal_id7MUdLpgmQ_Y(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class PROPS {
    /*package*/ static final SProperty read$Lqh8 = MetaAdapterFactory.getProperty(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L, 0x3f9799e4ca5f40e3L, "read");
    /*package*/ static final SProperty write$Lqw9 = MetaAdapterFactory.getProperty(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L, 0x3f9799e4ca5f40e4L, "write");
    /*package*/ static final SProperty execute$LqJa = MetaAdapterFactory.getProperty(0x248c097d53364d24L, 0x9241611e979642dbL, 0x3f9799e4ca5f40c8L, 0x3f9799e4ca5f40e5L, "execute");
  }
}
