package SysMod.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class Root__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x248c097d53364d24L, 0x9241611e979642dbL, 0x1031032eed056a08L, "SysMod.structure.Root");

  public static final SMethod<String> getTargetName_id7MUdLpglIiZ = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getTargetName").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8987556575347926207L).languageId(0x9241611e979642dbL, 0x248c097d53364d24L).build2();
  public static final SMethod<String> getType_id5_filGttXaL = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6435443048220971697L).languageId(0x9241611e979642dbL, 0x248c097d53364d24L).build2();
  public static final SMethod<String> getTargetName_id5_filGt$_ye = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getTargetName").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6435443048222709902L).languageId(0x9241611e979642dbL, 0x248c097d53364d24L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getTargetName_id7MUdLpglIiZ, getType_id5_filGttXaL, getTargetName_id5_filGt$_ye);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getTargetName_id7MUdLpglIiZ(@NotNull SNode __thisNode__) {
    return "root";
  }
  /*package*/ static String getType_id5_filGttXaL(@NotNull SNode __thisNode__) {
    return "u";
  }
  /*package*/ static String getTargetName_id5_filGt$_ye(@NotNull SNode __thisNode__) {
    return "root";
  }

  /*package*/ Root__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getTargetName_id7MUdLpglIiZ(node));
      case 1:
        return (T) ((String) getType_id5_filGttXaL(node));
      case 2:
        return (T) ((String) getTargetName_id5_filGt$_ye(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
