package SysMod.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Debian13 {
  public List<User> users = ListSequence.fromList(new ArrayList<User>());
  public Debian13() {
  }

  public class User {
    /*package*/ String name;
    /*package*/ String home;
    /*package*/ List<String> groups;

    public User(String name, String home, List<String> groups) {
      this.name = name;
      this.home = home;
      this.groups = groups;
    }

  }
  public static void main(String[] args) {

    Debian13 mySys = new Debian13();

    System.out.println("Groups");
    System.out.println("sudo groupadd -f docker");
    System.out.println("sudo groupadd -f dev");
    System.out.println("sudo groupadd -f furry");
    System.out.println("sudo groupadd -f hackers");
    System.out.println("sudo groupadd -f admin");
    System.out.println("sudo groupadd -f teachers");
    System.out.println("------");
    System.out.println("Users");
    {
      List<String> usergroup_a = ListSequence.fromList(new ArrayList<String>());
      ListSequence.fromList(usergroup_a).addElement("furry");
      ListSequence.fromList(usergroup_a).addElement("hackers");
      ListSequence.fromList(mySys.users).addElement(mySys.new User("baba", "/home/baba", usergroup_a));
    }
    {
      List<String> usergroup_b = ListSequence.fromList(new ArrayList<String>());
      ListSequence.fromList(usergroup_b).addElement("dev");
      ListSequence.fromList(usergroup_b).addElement("docker");
      ListSequence.fromList(usergroup_b).addElement("hackers");
      ListSequence.fromList(usergroup_b).addElement("admin");
      ListSequence.fromList(mySys.users).addElement(mySys.new User("arney", "/home/yes", usergroup_b));
    }
    {
      List<String> usergroup_c = ListSequence.fromList(new ArrayList<String>());
      ListSequence.fromList(usergroup_c).addElement("teachers");
      ListSequence.fromList(usergroup_c).addElement("admin");
      ListSequence.fromList(mySys.users).addElement(mySys.new User("joejoe", "/home/plp", usergroup_c));
    }
    for (User u : mySys.users) {
      System.out.println("if ! id -u " + u.name + "&>dev/null; then");
      System.out.println("    sudo useradd -m -d " + u.home + " -G " + String.join(",", u.groups) + " " + u.name);
      System.out.println("else");
      System.out.println("    sudo usermod -d " + u.home + " -G " + String.join(",", u.groups) + " " + u.name);
      for (String s : u.groups) {
        System.out.println("sudo -aG " + s + u.name);
      }
    }
    System.out.println("test");
  }
}
