package SysMod.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.ArrayList;
import java.io.File;
import java.io.PrintStream;
import java.io.FileOutputStream;
import java.io.IOException;

public class Debia {
  public Debia() {
  }
  private static void printUserScriptBlock(String username, String homeDir, List<String> groups) {
    String groupOptions = "";
    if (groups != null && !(ListSequence.fromList(groups).isEmpty())) {
      groupOptions = " -G " + String.join(",", groups);
    }
    String addHomeOptions = "";
    String modHomeOptions = "";

    if (homeDir != null && !(homeDir.isEmpty())) {
      addHomeOptions = " -m -d " + homeDir;
      modHomeOptions = " -d " + homeDir;
    }

    String useraddCmd = "$SUDO useradd" + addHomeOptions + groupOptions + " " + username;
    String usermodCmd = "$SUDO usermod" + modHomeOptions + groupOptions + " " + username;

    System.out.println("if ! id -u " + username + " &>/dev/null; then");
    System.out.println("    " + useraddCmd);
    System.out.println("else");
    System.out.println("    " + usermodCmd);
    System.out.println("fi");
  }
  private static void printUserScriptBlock(String username, List<String> groups) {
    String groupOptions = "";
    if (groups != null && !(ListSequence.fromList(groups).isEmpty())) {
      groupOptions = " -G " + String.join(",", groups);
    }

    String useraddCmd = "$SUDO useradd" + groupOptions + " " + username;
    String usermodCmd = "$SUDO usermod" + groupOptions + " " + username;

    System.out.println("if ! id -u " + username + " &>/dev/null; then");
    System.out.println("    " + useraddCmd);
    System.out.println("else");
    System.out.println("    " + usermodCmd);
    System.out.println("fi");
  }
  private static void printGroupScriptBlock(String group) {
    System.out.println("$SUDO groupadd -f " + group);
  }
  private static void printFolderConfig(String path, String owner, String group, boolean recursive, Map<String, List<String>> permissions) {
    String recursiveFlag = (recursive ? " -R" : "");
    System.out.println("$SUDO mkdir -p " + path);
    System.out.println("$SUDO chown" + recursiveFlag + " " + owner + ":" + group + " " + path);

    if (permissions != null && !(MapSequence.fromMap(permissions).isEmpty())) {
      List<String> aclEntries = ListSequence.fromList(new ArrayList<String>());
      Iterable<String> keys = MapSequence.fromMap(permissions).keySet();
      for (String key : keys) {
        String rule = ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(0) + ":" + key + ":" + ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(1);
        ListSequence.fromList(aclEntries).addElement(rule);
      }
      String cmd = "$SUDO setfacl";
      cmd += recursiveFlag;
      String conf = " -m " + String.join(",", aclEntries) + " " + path;
      cmd += conf;
      System.out.println(cmd);
      if (recursive) {
        String yes = "$SUDO setfacl" + recursiveFlag + " -d" + conf;
        System.out.println(yes);
      }
    }
  }
  private static void printFileConfig(String path, String owner, String group, Map<String, List<String>> permissions) {
    String dir;
    int lastslash = path.lastIndexOf('/');
    if (lastslash != -1) {
      dir = path.substring(0, lastslash);
    } else {
      dir = "";
    }
    if (!(dir.isEmpty())) {
      System.out.println("$SUDO mkdir -p " + dir);
    }
    System.out.println("$SUDO touch " + path);
    System.out.println("$SUDO chown" + " " + owner + ":" + group + " " + path);

    if (permissions != null && !(MapSequence.fromMap(permissions).isEmpty())) {
      List<String> aclEntries = ListSequence.fromList(new ArrayList<String>());
      Iterable<String> keys = MapSequence.fromMap(permissions).keySet();
      for (String key : keys) {
        String rule = ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(0) + ":" + key + ":" + ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(1);
        ListSequence.fromList(aclEntries).addElement(rule);
      }
      String cmd = "$SUDO setfacl";
      String conf = " -m " + String.join(",", aclEntries) + " " + path;
      cmd += conf;
      System.out.println(cmd);
    }
  }

  public static void main(String[] args) {
    String fn = "Debia" + "_sysmod" + ".sh";
    File outputFile = new File(fn);
    PrintStream originalOut = System.out;

    try (FileOutputStream fos = new FileOutputStream(outputFile, false)) {

      PrintStream ps = new PrintStream(fos);
      System.setOut(ps);
      Debia mySys = new Debia();
      System.out.println("#!/bin/bash");
      System.out.println("set -e");
      System.out.println("set -x");
      System.out.println("SUDO=''");
      System.out.println("if [ \"$EUID\" -ne 0 ]; then");
      System.out.println("    SUDO='sudo'");
      System.out.println("fi");
      System.out.println("if ! command -v setfacl >/dev/null 2>&1; then");
      System.out.println("    echo \"Installing ACL tools\"");
      System.out.println("    $SUDO apt update -y\n    $SUDO apt install -y acl\nfi");
      System.out.println("echo 'System Operation " + "Debia" + " ....'");
      System.out.println("echo 'Groups'");
      printGroupScriptBlock("furry");
      printGroupScriptBlock("hackers");
      System.out.println("echo '-------------------'");
      System.out.println("echo 'Users'");
      System.setOut(originalOut);
    } catch (IOException ioe) {
      originalOut.println("Could not write to ");
      ioe.printStackTrace(originalOut);
    } finally {
      System.setOut(originalOut);
    }
    try {
      String os = System.getProperty("os.name").toLowerCase();
      if (os.contains("win")) {
        new ProcessBuilder("cmd", "/c", "start", "", outputFile.getAbsolutePath()).start();
      } else if (os.contains("mac")) {
        new ProcessBuilder("open", outputFile.getAbsolutePath()).start();
      } else {
        new ProcessBuilder("xdg-open", outputFile.getAbsolutePath()).start();
      }

    } catch (IOException ioe) {
      System.err.println("Failed to open file: " + ioe.getMessage());
      ioe.printStackTrace();
    }


  }
}
