package SysMod.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.ArrayList;
import java.io.File;
import java.io.PrintStream;
import java.io.FileOutputStream;
import java.util.HashMap;
import java.io.IOException;

public class Debian13 {
  public Debian13() {
  }
  private static void printUserScriptBlock(String username, String homeDir, List<String> groups) {
    String groupOptions = "";
    if (groups != null && !(ListSequence.fromList(groups).isEmpty())) {
      groupOptions = " -G " + String.join(",", groups);
    }
    String addHomeOptions = "";
    String modHomeOptions = "";

    if (homeDir != null && !(homeDir.isEmpty())) {
      addHomeOptions = " -m -d " + homeDir;
      modHomeOptions = " -d " + homeDir;
    }

    String useraddCmd = "$SUDO useradd" + addHomeOptions + groupOptions + " " + username;
    String usermodCmd = "$SUDO usermod" + modHomeOptions + groupOptions + " " + username;

    System.out.println("if ! id -u " + username + " &>/dev/null; then");
    System.out.println("    " + useraddCmd);
    System.out.println("else");
    System.out.println("    " + usermodCmd);
    System.out.println("fi");
  }
  private static void printUserScriptBlock(String username, List<String> groups) {
    String groupOptions = "";
    if (groups != null && !(ListSequence.fromList(groups).isEmpty())) {
      groupOptions = " -G " + String.join(",", groups);
    }

    String useraddCmd = "$SUDO useradd" + groupOptions + " " + username;
    String usermodCmd = "$SUDO usermod" + groupOptions + " " + username;

    System.out.println("if ! id -u " + username + " &>/dev/null; then");
    System.out.println("    " + useraddCmd);
    System.out.println("else");
    System.out.println("    " + usermodCmd);
    System.out.println("fi");
  }
  private static void printGroupScriptBlock(String group) {
    System.out.println("$SUDO groupadd -f " + group);
  }
  private static void printFolderConfig(String path, String owner, String group, boolean recursive, Map<String, List<String>> permissions) {
    String recursiveFlag = (recursive ? " -R" : "");
    System.out.println("$SUDO mkdir -p " + path);
    System.out.println("$SUDO chown" + recursiveFlag + " " + owner + ":" + group + " " + path);

    if (permissions != null && !(MapSequence.fromMap(permissions).isEmpty())) {
      List<String> aclEntries = ListSequence.fromList(new ArrayList<String>());
      Iterable<String> keys = MapSequence.fromMap(permissions).keySet();
      for (String key : keys) {
        String rule = ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(0) + ":" + key + ":" + ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(1);
        ListSequence.fromList(aclEntries).addElement(rule);
      }
      String cmd = "$SUDO setfacl";
      cmd += recursiveFlag;
      String conf = " -m " + String.join(",", aclEntries) + " " + path;
      cmd += conf;
      System.out.println(cmd);
      if (recursive) {
        String yes = "$SUDO setfacl" + recursiveFlag + " -d" + conf;
        System.out.println(yes);
      }
    }
  }
  private static void printFileConfig(String path, String owner, String group, Map<String, List<String>> permissions) {
    String dir;
    int lastslash = path.lastIndexOf('/');
    if (lastslash != -1) {
      dir = path.substring(0, lastslash);
    } else {
      dir = "";
    }
    if (!(dir.isEmpty())) {
      System.out.println("$SUDO mkdir -p " + dir);
    }
    System.out.println("$SUDO touch " + path);
    System.out.println("$SUDO chown" + " " + owner + ":" + group + " " + path);

    if (permissions != null && !(MapSequence.fromMap(permissions).isEmpty())) {
      List<String> aclEntries = ListSequence.fromList(new ArrayList<String>());
      Iterable<String> keys = MapSequence.fromMap(permissions).keySet();
      for (String key : keys) {
        String rule = ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(0) + ":" + key + ":" + ListSequence.fromList(MapSequence.fromMap(permissions).get(key)).getElement(1);
        ListSequence.fromList(aclEntries).addElement(rule);
      }
      String cmd = "$SUDO setfacl";
      String conf = " -m " + String.join(",", aclEntries) + " " + path;
      cmd += conf;
      System.out.println(cmd);
    }
  }

  public static void main(String[] args) {
    String fn = "Debian13" + "_sysmod" + ".sh";
    File outputFile = new File(fn);
    PrintStream originalOut = System.out;

    try (FileOutputStream fos = new FileOutputStream(outputFile, false)) {

      PrintStream ps = new PrintStream(fos);
      System.setOut(ps);
      Debian13 mySys = new Debian13();
      System.out.println("#!/bin/bash");
      System.out.println("set -e");
      System.out.println("set -x");
      System.out.println("SUDO=''");
      System.out.println("if [ \"$EUID\" -ne 0 ]; then");
      System.out.println("    SUDO='sudo'");
      System.out.println("fi");
      System.out.println("if ! command -v setfacl >/dev/null 2>&1; then");
      System.out.println("    echo \"Installing ACL tools\"");
      System.out.println("    $SUDO apt update -y\n    $SUDO apt install -y acl\nfi");
      System.out.println("echo 'System Operation " + "Debian13" + " ....'");
      System.out.println("echo 'Groups'");
      printGroupScriptBlock("docker");
      printGroupScriptBlock("dev");
      printGroupScriptBlock("furry");
      printGroupScriptBlock("hackers");
      printGroupScriptBlock("admin");
      printGroupScriptBlock("teachers");
      System.out.println("echo '-------------------'");
      System.out.println("echo 'Users'");
      {
        List<String> usergroups_a = ListSequence.fromList(new ArrayList<String>());
        ListSequence.fromList(usergroups_a).addElement("furry");
        ListSequence.fromList(usergroups_a).addElement("hackers");
        printUserScriptBlock("baba", "/home/baba", usergroups_a);
      }
      {
        List<String> usergroups_b = ListSequence.fromList(new ArrayList<String>());
        ListSequence.fromList(usergroups_b).addElement("dev");
        ListSequence.fromList(usergroups_b).addElement("docker");
        ListSequence.fromList(usergroups_b).addElement("hackers");
        ListSequence.fromList(usergroups_b).addElement("admin");
        printUserScriptBlock("arney", usergroups_b);
      }
      {
        List<String> usergroups_c = ListSequence.fromList(new ArrayList<String>());
        ListSequence.fromList(usergroups_c).addElement("teachers");
        ListSequence.fromList(usergroups_c).addElement("admin");
        printUserScriptBlock("joejoe", "/home/plp", usergroups_c);
      }
      {
        Map<String, List<String>> permissions_a = MapSequence.fromMap(new HashMap<String, List<String>>());
        {
          List<String> userPerm_a0 = ListSequence.fromList(new ArrayList<String>());
          ListSequence.fromList(userPerm_a0).addElement("g");
          ListSequence.fromList(userPerm_a0).addElement("rwx");
          MapSequence.fromMap(permissions_a).put("furry", userPerm_a0);
        }
        {
          List<String> userPerm_b0 = ListSequence.fromList(new ArrayList<String>());
          ListSequence.fromList(userPerm_b0).addElement("u");
          ListSequence.fromList(userPerm_b0).addElement("---");
          MapSequence.fromMap(permissions_a).put("arney", userPerm_b0);
        }
        printFolderConfig("/furry", "root", "baba", true, permissions_a);
      }
      {
        Map<String, List<String>> permissions_b = MapSequence.fromMap(new HashMap<String, List<String>>());
        {
          List<String> userPerm_a1 = ListSequence.fromList(new ArrayList<String>());
          ListSequence.fromList(userPerm_a1).addElement("g");
          ListSequence.fromList(userPerm_a1).addElement("rwx");
          MapSequence.fromMap(permissions_b).put("hackers", userPerm_a1);
        }
        printFolderConfig("/hey/testers", "root", "hackers", false, permissions_b);
      }
      {
        Map<String, List<String>> permissions_a_0 = MapSequence.fromMap(new HashMap<String, List<String>>());
        {
          List<String> userPerm_a0_0 = ListSequence.fromList(new ArrayList<String>());
          ListSequence.fromList(userPerm_a0_0).addElement("g");
          ListSequence.fromList(userPerm_a0_0).addElement("rwx");
          MapSequence.fromMap(permissions_a_0).put("dev", userPerm_a0_0);
        }
        {
          List<String> userPerm_b0_0 = ListSequence.fromList(new ArrayList<String>());
          ListSequence.fromList(userPerm_b0_0).addElement("u");
          ListSequence.fromList(userPerm_b0_0).addElement("---");
          MapSequence.fromMap(permissions_a_0).put("baba", userPerm_b0_0);
        }
        printFileConfig("/secret/codes.txt", "root", "root", permissions_a_0);
      }
      System.setOut(originalOut);
    } catch (IOException ioe) {
      originalOut.println("Could not write to ");
      ioe.printStackTrace(originalOut);
    } finally {
      System.setOut(originalOut);
    }
    try {
      String os = System.getProperty("os.name").toLowerCase();
      if (os.contains("win")) {
        new ProcessBuilder("cmd", "/c", "start", "", outputFile.getAbsolutePath()).start();
      } else if (os.contains("mac")) {
        new ProcessBuilder("open", outputFile.getAbsolutePath()).start();
      } else {
        new ProcessBuilder("xdg-open", outputFile.getAbsolutePath()).start();
      }

    } catch (IOException ioe) {
      System.err.println("Failed to open file: " + ioe.getMessage());
      ioe.printStackTrace();
    }


  }
}
