package SysMod.sandbox;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class yes {
  public List<User> users = ListSequence.fromList(new ArrayList<User>());
  public yes() {
  }

  public class User {
    /*package*/ String name;
    /*package*/ String home;
    /*package*/ List<String> groups;

    public User(String name, String home, List<String> groups) {
      this.name = name;
      this.home = home;
      this.groups = groups;
    }

  }
  public static void main(String[] args) {

    yes mySys = new yes();

    System.out.println("Groups");
    System.out.println("------");
    System.out.println("Users");
    for (User u : mySys.users) {
      System.out.println("if ! id -u " + u.name + "&>dev/null; then");
      System.out.println("    sudo useradd -m -d " + u.home + " -G " + String.join(",", u.groups) + " " + u.name);
      System.out.println("else");
      System.out.println("    sudo usermod -d " + u.home + " -G " + String.join(",", u.groups) + " " + u.name);
      for (String s : u.groups) {
        System.out.println("sudo -aG " + s + u.name);
      }
    }
    System.out.println("test");
  }
}
